---
- hosts: wp_database
  tasks:
    - name: 'Instala mysql'
      apt:
        name: "{{ pacotes }}"
        state: latest
       # update_cache: yes
      vars:
        pacotes:
          - mysql-server-5.7
          - python-mysqldb
          - python3-pip     
          - python3.6-dev 
          - libmysqlclient-dev
        
      become: yes
    
    - name: mySQL-pyhton
      pip:
        name: PyMySQL
      become: yes
    
    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      become: yes
    
    - name: 'Cria o usuário do MySQL'
      mysql_user:
        login_user: root
        #  MySQL 5.7 allows local root logins using socket file
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '192.168.50.107'
      become: yes   
    - name: 'Configura MySQL para aceitar conexões remotas'
      copy:
        src: 'files/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify:
        - restart mysql

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

- hosts: wp_php
  tasks:
    - name: 'Instala o PHP, apache e lib'
      apt:
        name: "{{ pacotes }}"
        state: latest
      vars:
        pacotes:
          - php7.2
          - apache2
          - libapache2-mod-php7.2
          - php7.2-gd
          - php7.2-mysql 
      become: yes
    
    
    - name: 'Baixa o arquivo de instalacao do Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompacta o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes

    - copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do banco de dados'     
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
        - { regex: 'localhost', value: '192.168.50.108'}
      become: yes

    - name: 'Configura Apache para servir o Wordpress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes