---
- hosts: all
  tasks:
    - name: 'Instala o PHP, apache e lib'
      apt:
        name: "{{ pacotes }}"
        state: latest
      vars:
        pacotes:
          - php7.2
          - apache2
          - libapache2-mod-php7.2
          - php7.2-gd
          - mysql-server-5.7
          - python-mysqldb
          - php7.2-mysql 
          - python3-pip
          - python3.6-dev 
          - libmysqlclient-dev
      become: yes
    
    - name: mySQL-pyhton
      pip:
        name: PyMySQL
      become: yes
    
    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      become: yes
    
    - name: 'Cria o usuário do MySQL'
      mysql_user:
        login_user: root
        #  MySQL 5.7 allows local root logins using socket file
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes   
    
    - name: 'Baixa o arquivo de instalacao do Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompacta o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote: yes
      become: yes