---
- hosts: all
  tasks:
    - name: 'Instala o PHP7.2'
      apt:
        name: php7.2
        state: latest
      become: yes
    - name: 'Instala o Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Instala o modphp'
      apt:
        name: libapache2-mod-php7.2
        state: latest
      become: yes