---
- name: reboot remote hosts
  hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo

  vars_prompt:
    - name: ansible_become_pass
      prompt: "senha root"      

      tasks:
    - name: shutdown
      reboot: 
      sudo: yes

